### ISSUE TITLE
Error trying to get a INotifyCollectionChangedSynchronizedViewList collection Count

### ISSUE THREAD

**Issue by anavgar** [Cysharp/ObservableCollections#76]
When I try to get the Count of a INotifyCollectionChangedSynchronizedViewList collection I am forcet to do a cast, as there is an ambiguity error between `ICollection.Count` and `ICollection<T>.Count`

**Comment by neuecc** [comment]
INotifyCollectionChangedSynchronizedViewList is designed for use in binding scenarios, so it has both non-generic and generic interface definitions, making it cumbersome to use.
This is by design.
If you need to call it manually, please receive it as `IList<T>`.

**Comment by southernwind** [comment]
There is also an issue with binding using `x:Bind`.

The following code works without any problems:
`<TextBlock Text="{Binding Collection.Count, Mode=OneWay}" DataContext="{x:Bind ViewModel}"/>`

However, the following code results in a compilation error:
`<TextBlock Text="{x:Bind ViewModel.Collection.Count, Mode=OneWay}"/>`

Error Details:
`CS0229: Ambiguity between 'ICollection.Count' and 'ICollection<string>.Count'`

The issue appears to be caused by the addition of ICollection and ICollection<TView> to the interface when updating ObservableCollections from version 3.0.5 to 3.1.0.

**Comment by neuecc** [comment]
Thank you.
I think changing to an abstract class will solve the problem, so I'm trying to implement it.

**Comment by neuecc** [comment]
`v3.2.0` returns `NotifyCollectionChangedSynchronizedViewList` so solved.
